
package demo.hw.server;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-25T18:39:25.359+04:00
 * Generated source version: 3.0.4
 * 
 */
 
public class HelloWorldServer{

    protected HelloWorldServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new demo.hw.server.HelloWorldImpl();
        String address = "http://localhost:9090/HelloWorldImplPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new HelloWorldServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 